# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'upao' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for upao
  pod 'AppCenter/Push', '~> 1.0.1'
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'


  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'RNCViewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'upaoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'upao-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for upao-tvOS

  target 'upao-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
