# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'upao' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for upao
  pod 'AppCenter/Push', '~> 1.14.0'
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'

  target 'upaoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'upao-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for upao-tvOS

  target 'upao-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
